# Generated by Django 4.1.1 on 2022-09-14 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=7, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=8, verbose_name='Longitude')),
            ],
        ),
        migrations.CreateModel(
            name='Survivor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('age', models.PositiveSmallIntegerField(verbose_name='Age')),
                ('gender', models.CharField(max_length=20, verbose_name='Gender')),
                ('is_infected', models.BooleanField(default=False, verbose_name='Infected')),
                ('location', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='survivor', to='zssn.location')),
            ],
        ),
    ]
