# Generated by Django 4.1.1 on 2022-09-14 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zssn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survivor',
            name='location',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survivor', to='zssn.location'),
        ),
    ]
